# Generated by Django 4.2.3 on 2023-08-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketsystem',
            options={'verbose_name_plural': 'TicketSystem'},
        ),
    ]
