# Generated by Django 4.2.3 on 2023-08-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_ticketsystem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsystem',
            name='name',
            field=models.CharField(default='Abhi', max_length=100),
            preserve_default=False,
        ),
    ]
