# Generated by Django 4.2.3 on 2023-08-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_ticketsystem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsystem',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
