# Generated by Django 4.2.3 on 2023-08-03 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_images_delete_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='images',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos/thumbnails/'),
        ),
    ]
