# Generated by Django 4.2.3 on 2023-08-05 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_alter_images_options_images_uploaded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='media/videos/source videos', validators=[django.core.validators.FileExtensionValidator(['MP4', 'WebM', 'Ogg'])])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/videos/thumbnails/')),
                ('thumbnail_small', models.ImageField(blank=True, null=True, upload_to='media/videos/small thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='media/photos/source images'),
        ),
    ]
