# Generated by Django 4.2.3 on 2023-08-06 04:43

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0005_videos_alter_images_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='media/pdf/source pdf', validators=[django.core.validators.FileExtensionValidator(['PDF'])])),
                ('thumbnail', models.ImageField(upload_to='media/pdf/thumbnails/')),
                ('thumbnail_small', models.ImageField(blank=True, null=True, upload_to='media/pdf/small thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pdf',
            },
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterField(
            model_name='videos',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/videos/thumbnails/'),
            preserve_default=False,
        ),
    ]
