# Generated by Django 4.2.3 on 2023-08-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0006_pdf_alter_videos_options_alter_videos_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdf',
            options={'verbose_name_plural': 'PDF'},
        ),
    ]
