# Generated by Django 4.2.3 on 2023-09-15 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0008_alter_images_image_alter_images_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='media/photos/source images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='thumbnail_small',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos/small thumbnails/'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(upload_to='media/pdf/source pdf', validators=[django.core.validators.FileExtensionValidator(['PDF'])]),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='thumbnail',
            field=models.ImageField(upload_to='media/pdf/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='thumbnail_small',
            field=models.ImageField(blank=True, null=True, upload_to='media/pdf/small thumbnails/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='thumbnail',
            field=models.ImageField(upload_to='media/videos/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='thumbnail_small',
            field=models.ImageField(blank=True, null=True, upload_to='media/videos/small thumbnails/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='media/videos/source videos', validators=[django.core.validators.FileExtensionValidator(['MP4', 'WebM', 'Ogg'])]),
        ),
    ]
